// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6pssw2Z5J9GscJ4CtaBfwac5wCP2GPYM',
    appId: '1:228960169224:web:120d16b2bb8630458e90bd',
    messagingSenderId: '228960169224',
    projectId: 'lumiapp-829a7',
    authDomain: 'lumiapp-829a7.firebaseapp.com',
    storageBucket: 'lumiapp-829a7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrpmawahK9NYJtYLN6RYQufgz2Cpm0twY',
    appId: '1:228960169224:android:7abac631ea5c381e8e90bd',
    messagingSenderId: '228960169224',
    projectId: 'lumiapp-829a7',
    storageBucket: 'lumiapp-829a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlEtwHBy6QE52MDJPoqRyiKXWcRXQvTFA',
    appId: '1:228960169224:ios:b99ba14c57606e4f8e90bd',
    messagingSenderId: '228960169224',
    projectId: 'lumiapp-829a7',
    storageBucket: 'lumiapp-829a7.appspot.com',
    iosClientId: '228960169224-78ge43kp3vsqep779mgdm9hl66tldsea.apps.googleusercontent.com',
    iosBundleId: 'com.example.lumiapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlEtwHBy6QE52MDJPoqRyiKXWcRXQvTFA',
    appId: '1:228960169224:ios:35a90139f8371a1e8e90bd',
    messagingSenderId: '228960169224',
    projectId: 'lumiapp-829a7',
    storageBucket: 'lumiapp-829a7.appspot.com',
    iosClientId: '228960169224-p9k4t6u0cdrkrlkduv813kh0ni9rtsmq.apps.googleusercontent.com',
    iosBundleId: 'com.example.lumiapp.RunnerTests',
  );
}
